#!/usr/bin/env python3
"""
Builds dist/ — the public version of Desk Screen, for Vercel or any static
host.

The public build carries only the generative ambient engine. Spotify is left
out because it needs each visitor's own Premium account and Spotify caps a
development-mode app at five people; the music/ folder is left out because
those are your files, not the internet's. Anyone who opens the public site
gets artwork and endless original music with nothing to sign in to.

    python3 build-public.py        then deploy dist/

Run sync.py first if you have changed the images.
"""

import os
import re
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
DIST = os.path.join(ROOT, "dist")

KEEP = [

    "style.css",

    "app.js",

    "engine-ambient.js",

    "engine-files.js",

    "backgrounds.js",

    "tracks.js",

    "config.js",
    

]
PUBLIC_CONFIG = """/* Generated by build-public.py — the public build has no accounts. */
window.CONFIG = {
  mode: "ambient",
  clientId: "",
  playlist: "",
  volume: 0.6,
};
"""

HEAD_EXTRAS = """<meta name="description" content="A still image and endless original ambient music, for the screen you are not working on.">
<meta name="theme-color" content="#0b0b0f">
<meta property="og:title" content="Desk Screen">
<meta property="og:description" content="A still image and endless original ambient music, for the screen you are not working on.">
<meta property="og:type" content="website">
<link rel="icon" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 32 32'%3E%3Crect width='32' height='32' rx='7' fill='%230b0b0f'/%3E%3Ccircle cx='16' cy='16' r='9' fill='none' stroke='%23f8f6f2' stroke-opacity='.55' stroke-width='1.5'/%3E%3Cpath d='M13.5 11.4v9.2a.6.6 0 0 0 .92.5l7.1-4.6a.6.6 0 0 0 0-1L14.42 10.9a.6.6 0 0 0-.92.5z' fill='%23f8f6f2'/%3E%3C/svg%3E">
"""


def main():
    if not os.path.isdir(os.path.join(ROOT, "art")):
        sys.exit("no art/ folder — nothing to build")

    # Vercel writes .vercel/ into dist/ when you first deploy from there.
    # Losing it means the next deploy asks you to pick a project all over
    # again, so it survives the rebuild.
    keepsakes = {}
    for name in (".vercel", ".gitignore"):
        path = os.path.join(DIST, name)
        if os.path.exists(path):
            stash = os.path.join(ROOT, ".build-keep-" + name.lstrip("."))
            if os.path.exists(stash):
                shutil.rmtree(stash, ignore_errors=True) if os.path.isdir(stash) else os.remove(stash)
            shutil.move(path, stash)
            keepsakes[name] = stash

    fresh = True
    if os.path.isdir(DIST):
        try:
            shutil.rmtree(DIST)
        except OSError:
            # some folders (network shares, synced drives) refuse deletes;
            # overwriting still produces a correct build
            fresh = False
            print("could not clear dist/ — overwriting it instead")
    os.makedirs(DIST, exist_ok=True)

    for name, stash in keepsakes.items():
        shutil.move(stash, os.path.join(DIST, name))

    # Refresh backgrounds.js from the folders — but only where ffmpeg exists
    # to read poster frames and average colours. On a build server without it,
    # the committed backgrounds.js is better than one sync.py would write.
    if shutil.which("ffmpeg"):
        try:
            subprocess.run([sys.executable, os.path.join(ROOT, "sync.py")],
                           cwd=ROOT, check=True, capture_output=True)
        except Exception:
            print("sync.py did not run — using the existing backgrounds.js")
    else:
        print("no ffmpeg here — using the committed backgrounds.js")

    for name in KEEP:
        source = os.path.join(ROOT, name)
        if not os.path.exists(source):
            sys.exit("missing " + name)
        shutil.copy2(source, os.path.join(DIST, name))

    def copy_folder(name):
        """Only the files the page actually lists — sync.py ignores anything
        in a subfolder, so a subfolder is a place to park things, not to ship."""
        source = os.path.join(ROOT, name)
        if not os.path.isdir(source):
            return
        target = os.path.join(DIST, name)
        os.makedirs(target, exist_ok=True)
        for entry in sorted(os.listdir(source)):
            path = os.path.join(source, entry)
            if os.path.isfile(path) and not entry.startswith("."):
                shutil.copy2(path, os.path.join(target, entry))

    copy_folder("art")
    copy_folder("video")
    copy_folder("music")
    

    if os.path.exists(os.path.join(ROOT, "vercel.json")):
        shutil.copy2(os.path.join(ROOT, "vercel.json"), os.path.join(DIST, "vercel.json"))


    with open(os.path.join(ROOT, "index.html"), encoding="utf-8") as f:
        html = f.read()

    # the public build has no Spotify and no local files
   # keep local file playback in the public build
    html = html.replace('<script src="engine-spotify.js"></script>\n', "")
    html = html.replace("</head>", HEAD_EXTRAS + "</head>")

    with open(os.path.join(DIST, "index.html"), "w", encoding="utf-8") as f:
        f.write(html)

    leftovers = re.findall(r'src="(engine-spotify)\.js"', html)
    if leftovers:
        sys.exit("index.html still references " + ", ".join(leftovers))

    videos = os.path.join(DIST, "video")
    clips = [n for n in os.listdir(videos)] if os.path.isdir(videos) else []
    weight = sum(os.path.getsize(os.path.join(videos, n)) for n in clips)
    if weight:
        print("video/ is %.1f MB of that — a visitor loads one clip, not all of them"
              % (weight / 1024 / 1024))

    total = 0
    for base, _dirs, files in os.walk(DIST):
        for name in files:
            total += os.path.getsize(os.path.join(base, name))

    print("dist/ built — %.1f MB" % (total / 1024 / 1024))
    if not fresh:
        print("dist/ was overwritten rather than rebuilt — delete it by hand")
        print("if you have removed any artwork since the last build.")
    print()
    print("Deploy it:")
    print("    cd dist && npx vercel --prod")
    print()
    print("or drag the dist folder onto vercel.com/new.")


if __name__ == "__main__":
    main()
