/* ---------------------------------------------------------------------------
   Desk Screen — service worker.

   Caches the shell (HTML, CSS, JS, fonts) on first load so the screen opens
   instantly even on bad campus Wi-Fi, and works fully offline for the
   generative ambient and local-files engines. YouTube and Spotify still need
   a connection.

   Strategy: cache-first for shell assets, network-first for art images so
   new art you drop into art/ shows up without clearing cache.
--------------------------------------------------------------------------- */

const CACHE = "desk-screen-v1";

/* Shell assets — cached on install, served from cache indefinitely */
const SHELL = [
  "/",
  "/index.html",
  "/style.css",
  "/app.js",
  "/intention.js",
  "/engine-ambient.js",
  "/engine-files.js",
  "/engine-spotify.js",
  "/engine-youtube.js",
  "/config.js",
  "/tracks.js",
  "/backgrounds.js",
];

self.addEventListener("install", function (e) {
  e.waitUntil(
    caches.open(CACHE).then(function (cache) {
      /* Best-effort: some files (config.js, tracks.js) may 404 on a fresh
         clone; that is fine — they are regenerated by sync.py */
      return Promise.allSettled(
        SHELL.map(function (url) { return cache.add(url).catch(function () {}); })
      );
    }).then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener("activate", function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(
        keys.filter(function (k) { return k !== CACHE; })
            .map(function (k) { return caches.delete(k); })
      );
    }).then(function () { return self.clients.claim(); })
  );
});

self.addEventListener("fetch", function (e) {
  const url = new URL(e.request.url);

  /* Only handle same-origin GET requests */
  if (e.request.method !== "GET" || url.origin !== self.location.origin) return;

  /* Art and video: network-first so newly added files show up immediately */
  if (url.pathname.startsWith("/art/") || url.pathname.startsWith("/video/")) {
    e.respondWith(
      fetch(e.request).then(function (res) {
        const clone = res.clone();
        caches.open(CACHE).then(function (c) { c.put(e.request, clone); });
        return res;
      }).catch(function () {
        return caches.match(e.request);
      })
    );
    return;
  }

  /* Everything else: cache-first */
  e.respondWith(
    caches.match(e.request).then(function (cached) {
      if (cached) return cached;
      return fetch(e.request).then(function (res) {
        if (res && res.status === 200 && res.type !== "opaque") {
          const clone = res.clone();
          caches.open(CACHE).then(function (c) { c.put(e.request, clone); });
        }
        return res;
      });
    })
  );
});
